name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - edited
      - synchronize

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install deps
        uses: ./.github/workflows/install

      - name: Run the tests
        run: npm test


